service: mood-sing-api
app: mood-sing-api
org: aasthakhanna

provider:
  name: aws
  runtime: python3.7

custom:
  wsgi:
    app: mood_sing/app.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
